### ISSUE TITLE
SECURITY: OWASP SQL Injection

### ISSUE THREAD

**Issue by davorpa** [SerxoLaxe/proyectoHAB#35]
## Description

Raw parameters from request must be sanatized before use in a query. If not, a SQL injection can reveal sensitive data or even change it or delete depend on connect user access rights.

## Evidence

https://github.com/SerxoLaxe/proyectoHAB-backend/blob/6908e69e7ca19d446ae009132b58757c5bd5661a/controllers/experiencias/buscarExperiencias.js#L57-L84

Sure that there are more endpoints.

Here a simple example of how to reproduce it: [AbdulMoizAli/SQL-Injection-Demo](https://github.com/AbdulMoizAli/SQL-Injection-Demo)

## How to fix it

- Use prepared statements.  [sidorares/node-mysql2/documentation/Prepared-Statements.md](https://github.com/sidorares/node-mysql2/blob/master/documentation/Prepared-Statements.md)
  
- Escape parameters before append to query string.
  Both mysql2 and mysql node drivers are compatible so... reading [mysqljs/mysql#escaping-query-values](https://github.com/mysqljs/mysql#escaping-query-values)  it's possible escape values using one of `mysql.escape()`, `connection.escape()` or `pool.escape()` utility methods. Take also a look at [mysql2 docs](https://github.com/sidorares/node-mysql2/tree/master/documentation).

I hope this helps :hugs:

**Comment by SerxoLaxe** [comment]
Thanks for the input :bow:

**Comment by davorpa** [comment]
You're welcome :wink:. A plesure to help

**Comment by oscarb65** [comment]
We are very grateful for your input.
